# Generated by Django 3.0 on 2020-09-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='город')),
                ('phone_number', models.CharField(max_length=15, verbose_name='телефон')),
                ('email', models.CharField(max_length=20, verbose_name='электронная почта')),
                ('post_address', models.CharField(max_length=128, verbose_name='почтовый адрес')),
            ],
        ),
    ]
