# Generated by Django 3.1.2 on 2020-10-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_acitve',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_acitve',
            field=models.BooleanField(default=True),
        ),
    ]
